---
kind: pipeline
name: default

steps:
- name: test
  image: golang:latest
  commands:
    - go vet
    - go test -v -cover

- name: build
  image: golang:latest
  commands:
    - go build -o main main.go

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: docker.pkg.github.com
    repo: docker.pkg.github.com/kenwang815/drone-with-go/drone-golang
    auto_tag: true
    auto_tag_suffix: linux-amd64

- name: ssh-deploy
    image: appleboy/drone-ssh
    settings:
      host: hyzen.ddns.net
      username: drone
      port: 22
      key:
        from_secret: ssh_key
      script:
        - docker pull docker.pkg.github.com/kenwang815/drone-with-go/drone-golang:linux-amd64
        - docker run --rm docker.pkg.github.com/kenwang815/drone-with-go/drone-golang:linux-amd64
